"""empty message

Revision ID: 39326bf6587a
Revises: 4638c95cc17d
Create Date: 2024-04-11 11:20:42.940064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39326bf6587a'
down_revision = '4638c95cc17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_event_places', 'events', ['event_id'], ['id'])

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
