"""empty message

Revision ID: aed2d873ca8c
Revises: 97d37cb3f0c6
Create Date: 2024-04-07 23:52:11.858105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed2d873ca8c'
down_revision = '97d37cb3f0c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('montant', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('mode_paiement', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date_paiement', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('statut', sa.String(length=255), nullable=False))

    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salles', schema=None) as batch_op:
        batch_op.drop_column('adresse')

    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_column('statut')
        batch_op.drop_column('date_paiement')
        batch_op.drop_column('mode_paiement')
        batch_op.drop_column('montant')

    # ### end Alembic commands ###
